REPLACE="
/system/app/AnalyticsCore
/system/app/facebook-appmanager
/system/app/Joyose
/system/app/MiuiDaemon
/system/app/MSA-Global
/system/app/MIDrop
/system/app/MIUIMiPicks
/system/app/PaymentService
/system/app/XiaomiSimActivateService
/system/app/InMipay
/system/priv-app/facebook-installer
/system/priv-app/facebook-services
/system/priv-app/MIUIGlobalMinusScreen
/system/priv-app/MIUIYellowPageGlobal
/system/product/app/YouTube
/system/vendor/app/MipayService
/system/vendor/app/SoterService
/system/vendor/app/IFAAService
"
